### ISSUE TITLE
Conda-forge and licensing question

### ISSUE THREAD

**Issue by d-cunningham** [databrickslabs/geoscan#31]
I would like to add geoscan to the conda-forge (https://conda-forge.org/) to make the package accessible to a wider user base. To add the package to the conda-forge the package's license needs to permit redistribution. However, the license associated with geoscan does not explicitly say redistribution is permitted like other open source licenses. Does the Databricks license allow redistribution?

**Comment by aamend** [comment]
Thanks for flagging this. Although the databricks license prevents users from redistributing this project, nothing stops us from making that library also available on conda forge to make it accessible to a wider user base. Would that be OK?

**Comment by d-cunningham** [comment]
Am I understanding your comment correctly? A user of geoscan (like myself) cannot add the geoscan project to the conda-forge due to licensing issues, but one of the geoscan project owners is able to. For me, it doesn't matter who makes the project available on the conda-forge as long as we can find a way to add it. I would be happy to help in any way possible.

**Comment by aamend** [comment]
Correct. As owner of the code, we can release it as-is to nexus (like I did for scala) and / or elsewhere. Appreciate if you could give me some pointers re. conda-forge (personally never used it). We'll look into this internally.
