### ISSUE TITLE
Geoscan requires .jar files to run

### ISSUE THREAD

**Issue by oleksandrkarasov** [databrickslabs/geoscan#63]
Thank you for this very promising tool! I am trying to run the Geoscan algorithm in Databricks platform. However, the personalized model cannot be run, there seem to be some issues with .jar dependencies: "TypeError: 'JavaPackage' object is not callable". When I installed geoscan-0.1.jar from here: https://repo1.maven.org/maven2/com/databricks/labs/geoscan/0.1/ to Compute-My Cluster-Libraries, I started receiving another error: "Py4JError: An error occurred while calling o521.getParam". Could you, please, clarify what can be the problem?

**Comment by oleksandrkarasov** [comment]
Thank you for your response! I am adding this dependency as
`%scala
<dependency>
   <groupId>com.databricks.labs</groupId>
   <artifactId>geoscan</artifactId>
   <version>0.1</version>
</dependency>`

However, at the stage 
`from geoscan import Geoscan
import mlflow

with mlflow.start_run(run_name='GEOSCAN') as run:
 
  geoscan = Geoscan() \
    .setLatitudeCol('latitude') \
    .setLongitudeCol('longitude') \
    .setPredictionCol('cluster') \
    .setEpsilon(200) \
    .setMinPts(20)
  
  mlflow.log_param('epsilon', 200)
  mlflow.log_param('minPts', 20)
  
  model = geoscan.fit(points_sampled)
  mlflow.spark.log_model(model, "geoscan")
  run_id = run.info.run_id`

I receive error "TypeError: 'JavaPackage' object is not callable". Maybe I need installing Maven inside Databricks cluster first?

**Comment by aamend** [comment]
Yes, library needs to be installed at the cluster level (hence before Spark context is being instantiated). Let me know how it works. 

FYI, I tested the whole solution on 9.x runtime with no problem, was facing minor issues on 10.x related to MLFlow.

**Comment by oleksandrkarasov** [comment]
Dear Antoine,
I installed jdk first and then maven (please, have a look at the attached notebook in zipped
[notebook1.zip](https://github.com/databrickslabs/geoscan/files/8952891/notebook1.zip)
 .html) but still 'JavaPackage' object is not callable". I am using 9.x cluster. Could you, please, indicate what in the installation process should be corrected to get rid of this java problem?
